version: "3"

services:
  app-order-service:
    depends_on:
      - database
    restart: unless-stopped
    build: ./code
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'testdb'
    ports:
      - 8081:5000
    volumes:
      - ./code:/app
    command: python ./app.py


  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - scalablel-db:/var/lib/mysql
      - ./code/db:/docker-entrypoint-initdb.d


volumes:
    scalablel-db:
      driver: local
